- name: get dotfiles repo
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
  become: yes
  become_user: "{{ default_user }}"

- name: ensure that all dootfiles are links.
  shell: "ls -F {{ default_home }}/{{ item }}"
  register: existing_dotfile_info
  failed_when: false
  check_mode: no
  changed_when: false
  with_items: "{{ dotfiles_files }}"
  become: yes
  become_user: "{{ default_user }}"

- name: remove non link dotfiles
  file:
    path: "{{ default_home }}/{{ dotfiles_files[item.0] }}"
    state: absent
  when: "'@' not in item.1.stdout"
  with_indexed_items: "{{ existing_dotfile_info.results }}"
  become: yes
  become_user: "{{ default_user }}"

- name: link dotfiles
  file:
    src: "{{ dotfiles_repo_local_destination }}/{{ item }}"
    dest: "{{ default_home }}/{{ item }}"
    state: link
  with_items: "{{ dotfiles_files }}"
  become: yes
  become_user: "{{ default_user }}"
