
- name: ensure apt-transport-https is installed.
  apt:
    name: apt-transport-https
    state: present

- name: add nodesource apt key.
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: add nodesource repository.
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }} xenial main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} xenial main"
  register: node_repo


- name: ensure Node.js is installed.
  apt:
    update_cache: yes
    name: nodejs={{ nodejs_version|regex_replace('x', '') }}*
    state: present
