- name: install tmux packages
  apt:
    name: tmux
    state: present
    update_cache: yes

- name: install ruby
  apt:
    name: ruby
    state: present
    update_cache: yes

- name: install tmuxinator
  gem:
      name: tmuxinator
      state: present
